# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-27 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0009_periodictask_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodictask',
            name='name',
            field=models.CharField(help_text='Useful description', max_length=1000, unique=True, verbose_name='name'),
        ),
    ]
